### ISSUE TITLE
Meta: pre-open-sourcing checklist

### ISSUE THREAD

**Issue by benjaminion** [PegaSysEng/BeaconChain#57]
- [x] Install _Code of Conduct_, _Contributing_ etc.  #51 
- [x] Add copyright notices to all source files #56 
- [x] Automate the CLA signing on first commit
- [x] Create our own Gitter channel (or use Pantheon's?) and reference it in the CLA etc.
- [x] Link to Pantheon's coding conventions from the relevant places
- [x] Automate the build process on commit (Spotless check at a minimum)
- [x] Move to PegaSysEng repo?
- [x] Decide on a cool name?
